CREATE TABLE urls (
    id INT AUTO_INCREMENT PRIMARY KEY,
    url VARCHAR(255) NOT NULL,
    website_title VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    approved TINYINT(1) NOT NULL DEFAULT 0
);

ALTER TABLE urls
    ADD COLUMN website_title VARCHAR(255) NOT NULL AFTER url;

ALTER TABLE urls
    ADD COLUMN approved TINYINT(1) NOT NULL DEFAULT 0 AFTER timestamp;